### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by TheCodeTraveler** [brminnick/TextMood_TwilioBlog#1]
![architecture](https://user-images.githubusercontent.com/13558917/43020214-2a1514cc-8c14-11e8-8916-47678569ebac.png)
![cognitiveservices_createnewresource](https://user-images.githubusercontent.com/13558917/43020215-2a29cf70-8c14-11e8-8988-c281308cd45f.png)
![cognitiveservices_createtextanalysis](https://user-images.githubusercontent.com/13558917/43020216-2a3dff68-8c14-11e8-8c1d-56ac21a3b6a2.png)
![cognitiveservices_deploymentinprogress](https://user-images.githubusercontent.com/13558917/43020217-2a51d858-8c14-11e8-93d8-e892e5458b1f.png)
![cognitiveservices_deploymentsucceeded](https://user-images.githubusercontent.com/13558917/43020218-2a669e3c-8c14-11e8-95df-619275893cc4.png)
![cognitiveservices_getapikey](https://user-images.githubusercontent.com/13558917/43020219-2a7ce818-8c14-11e8-99f7-d48f15c3553a.png)
![functions_addprojectjson](https://user-images.githubusercontent.com/13558917/43020220-2a953378-8c14-11e8-97a0-1742227c6d48.png)
![functions_advancededitor](https://user-images.githubusercontent.com/13558917/43020221-2aa6dcfe-8c14-11e8-8295-93f4d3d96020.png)
![functions_createafunction](https://user-images.githubusercontent.com/13558917/43020222-2abafae0-8c14-11e8-8554-ef210f0d02bf.png)
![functions_createfunction](https://user-images.githubusercontent.com/13558917/43020223-2b003eb6-8c14-11e8-8020-2460b5f06296.png)
![functions_createnewfunction](https://user-images.githubusercontent.com/13558917/43020224-2b14267e-8c14-11e8-8846-d26d2d539c29.png)
![functions_createthisfunction](https://user-images.githubusercontent.com/13558917/43020225-2b2763f6-8c14-11e8-9daf-2f6debca1ac7.png)
![functions_deploymentinprogress](https://user-images.githubusercontent.com/13558917/43020226-2b39e3f0-8c14-11e8-8a68-974900abca03.png)
![functions_functionjson](https://user-images.githubusercontent.com/13558917/43020227-2b4d3ed2-8c14-11e8-8fdf-bf46560bd9bb.png)
![functions_functionurl](https://user-images.githubusercontent.com/13558917/43020228-2b669332-8c14-11e8-9568-0a26547b829c.png)
![functions_getfunctionurl](https://user-images.githubusercontent.com/13558917/43020229-2b7b0150-8c14-11e8-996d-938c026278fb.png)
![functions_gotoresource](https://user-images.githubusercontent.com/13558917/43020231-2b9174e4-8c14-11e8-91ba-e30ccfa3118d.png)
![functions_projectjson](https://user-images.githubusercontent.com/13558917/43020232-2ba21704-8c14-11e8-853d-ae9ca851890c.png)
![functions_viewfiles](https://user-images.githubusercontent.com/13558917/43020233-2bb7cf2c-8c14-11e8-8f26-5a82b6c0a87f.png)

**Comment by TheCodeTraveler** [comment]
![architecture](https://user-images.githubusercontent.com/13558917/43020583-5869008a-8c15-11e8-95cc-7779b22baa7b.png)

**Comment by TheCodeTraveler** [comment]
![architecture](https://user-images.githubusercontent.com/13558917/43020603-66513e1a-8c15-11e8-928f-878ce536fd86.png)

**Comment by TheCodeTraveler** [comment]
![github_download](https://user-images.githubusercontent.com/13558917/43021037-13dfed6e-8c17-11e8-946e-baf30502104b.png)

**Comment by TheCodeTraveler** [comment]
![functions_rightclickpublish](https://user-images.githubusercontent.com/13558917/43021578-fe004e56-8c18-11e8-97cc-3a79dd3fe2e5.png)
![functions_createnew](https://user-images.githubusercontent.com/13558917/43021579-fe1eaa7c-8c18-11e8-8545-4d5cb1a058ae.png)
![functions_publish](https://user-images.githubusercontent.com/13558917/43021580-fe6b21a4-8c18-11e8-88d3-9de11ad17c96.png)

**Comment by TheCodeTraveler** [comment]
![functions_create](https://user-images.githubusercontent.com/13558917/43049731-aad2e488-8db1-11e8-8291-f8bf297ea281.png)
![functions_createnewstorageaccount](https://user-images.githubusercontent.com/13558917/43049732-ab104c9c-8db1-11e8-8ea7-182837384c78.png)
![functions_newstorageaccount](https://user-images.githubusercontent.com/13558917/43049733-ab26f24e-8db1-11e8-8421-ea121903e6c2.png)
![functions_configurehostingplan](https://user-images.githubusercontent.com/13558917/43049734-ab3d2028-8db1-11e8-889f-0cf28cd1a1f0.png)
![functions_newhostingplan](https://user-images.githubusercontent.com/13558917/43049735-ab51eabc-8db1-11e8-94eb-7853331fad33.png)
![functions_newresourcegroup](https://user-images.githubusercontent.com/13558917/43049736-ab6769e6-8db1-11e8-89c9-c18b9d1c2bcf.png)
![functions_createappservice](https://user-images.githubusercontent.com/13558917/43049737-ab7beb6e-8db1-11e8-8bd0-251194acfee5.png)

**Comment by TheCodeTraveler** [comment]
![functions_deployingappservice](https://user-images.githubusercontent.com/13558917/43049839-7b3710f8-8db3-11e8-9f79-ce24c77c90c1.png)

**Comment by TheCodeTraveler** [comment]
![functionsurl_resourcegroup](https://user-images.githubusercontent.com/13558917/43050243-4b24c692-8dba-11e8-8ab3-16656077a73f.png)
![textmoodfunction](https://user-images.githubusercontent.com/13558917/43050244-4b3a2802-8dba-11e8-9a90-4467470ac2fa.png)

**Comment by TheCodeTraveler** [comment]
![publish](https://user-images.githubusercontent.com/13558917/43050274-eb039328-8dba-11e8-8c2f-eacf72d8c9f0.png)

**Comment by TheCodeTraveler** [comment]
![getfunctionurl](https://user-images.githubusercontent.com/13558917/43050298-6d28cd46-8dbb-11e8-9442-b1dfa85ada24.png)

**Comment by TheCodeTraveler** [comment]
![buynewnumber](https://user-images.githubusercontent.com/13558917/43050467-1fb08646-8dbe-11e8-8d8b-14727373dba2.png)
![webhook](https://user-images.githubusercontent.com/13558917/43050468-1fc93772-8dbe-11e8-8513-4142eb052299.png)
![buy number](https://user-images.githubusercontent.com/13558917/43050469-1fe11158-8dbe-11e8-982d-3f608ad066c7.png)
![buy this number](https://user-images.githubusercontent.com/13558917/43050470-1ff6197c-8dbe-11e8-8364-9cafe5f0b9ca.png)
![setup number](https://user-images.githubusercontent.com/13558917/43050471-200b6ff2-8dbe-11e8-8187-df1a964399f9.png)
![buy a number](https://user-images.githubusercontent.com/13558917/43050472-20250a98-8dbe-11e8-88e9-d059dac13cca.png)

**Comment by TheCodeTraveler** [comment]
![buynewnumber](https://user-images.githubusercontent.com/13558917/43050486-3d85fd54-8dbe-11e8-82aa-4cd94737a05f.png)

**Comment by brminnick** [comment]
![webhook](https://user-images.githubusercontent.com/13558917/43050518-da109ad0-8dbe-11e8-926a-884e8585fde5.png)

**Comment by brminnick** [comment]
![img_9b0f93ea19bd-1](https://user-images.githubusercontent.com/13558917/43050538-2293d2cc-8dbf-11e8-8932-eba5cbeb371c.jpeg)

**Comment by TheCodeTraveler** [comment]
![happy](https://user-images.githubusercontent.com/13558917/43050543-4ca5cbb0-8dbf-11e8-8c37-82752d265432.png)

**Comment by TheCodeTraveler** [comment]
![endpoint](https://user-images.githubusercontent.com/13558917/43050639-5f84c6bc-8dc1-11e8-9fd3-f992efe5d12c.png)

**Comment by TheCodeTraveler** [comment]
<img width="101" alt="image" src="https://user-images.githubusercontent.com/13558917/43158648-0c989684-8f35-11e8-96ae-f92dea21f19b.png">

**Comment by TheCodeTraveler** [comment]
![webhook](https://user-images.githubusercontent.com/13558917/43158659-12b3bb66-8f35-11e8-9b19-e295132ec349.png)

**Comment by TheCodeTraveler** [comment]
![webhook](https://user-images.githubusercontent.com/13558917/43158699-2d545b7e-8f35-11e8-8e47-d120024aa948.png)

**Comment by TheCodeTraveler** [comment]
![file new project](https://user-images.githubusercontent.com/13558917/44055253-a87f15ea-9ef9-11e8-8c68-b3869a842886.png)

**Comment by TheCodeTraveler** [comment]
![new azure function](https://user-images.githubusercontent.com/13558917/44055505-6e28bc6a-9efa-11e8-9e10-3ed99272e249.png)

**Comment by TheCodeTraveler** [comment]
![new function setup](https://user-images.githubusercontent.com/13558917/44056404-fda59be0-9efc-11e8-9461-f2397d7fd33f.png)

**Comment by TheCodeTraveler** [comment]
![unload project](https://user-images.githubusercontent.com/13558917/44056895-841fdc02-9efe-11e8-997f-e118d359f8cc.png)

**Comment by TheCodeTraveler** [comment]
![edit csproj](https://user-images.githubusercontent.com/13558917/44057516-4d3e0a22-9f00-11e8-962f-aba2a7204af0.png)
